project:
  type: website
  output-dir: docs

website:
  title: "Estimated Latent Scores and Sum Scores"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true